### ISSUE TITLE
A 'squarify' feature

### ISSUE THREAD

**Issue by Aiena-g** [zeffii/mesh_tinyCAD#37]
Hmm was going to call it 'squarify' but then noticed https://github.com/laserson/squarify project already took that name and its also a name of an algo.

Anyway below is a graphical description of it. I think the other algo also does something similar but in 2D.

![feature request](https://cloud.githubusercontent.com/assets/5725991/12667624/30243cc0-c674-11e5-92d0-2677547915d0.png)

**Comment by zeffii** [comment]
This might be tricky for the general (and most common) cases. Are you talking about just edge based geometry (because adding support for Faces adds an extra level of complexity). I need to understand this better before going into prediction mode :)

![screen_demo](https://cloud.githubusercontent.com/assets/619340/12671475/20474f44-c670-11e5-8e34-20cecc096443.png)

I don't think the shape can be propagated downwards as easy as it was to make the suggestion. Extra information (ie selection information) must be present to provide hints to the algorithm. Maybe you can explain in more detail various scenarios of before and after. Maybe i'm thinking of scenarios which are more complex than the potential use--cases that you had in mind. 

hence, i need more info to let the brain think about this :)

**Comment by Aiena-g** [comment]
I was doing a bit of research into it. And I noticed that it is most likely hard to implement because of the varied ways in which geometry can flow. I sadly discovered this after posting the request will mull over it some more and see if other ideas come.

**Comment by zeffii** [comment]
no harm in thinking about it. -- here's an outline node I started for Sverchok, but didn't manage to finish.. https://github.com/nortikin/sverchok/issues/623
