### ISSUE TITLE
Can't bind a key

### ISSUE THREAD

**Issue by BloodyRain2k** [zeffii/mesh_tinyCAD#42]
I've been using the standalone version of XALL for 2.67 so far until I found this whole thing as a package and I had the standalone bound to alt x by opening the 'w' menu and rightclicking it which offered the keybinding menu.

But this package does for some reason not : ( when I rightclick the submenu nothing comes up and when I rightclick the XALL in the submenu all entries are there except the keybind one.

Now I don't know if this is an api issue with Blender or if there's a something that can be added to the scripts that makes it show up but in the slim case it's the latter it'd be nice if that could be added.

A piemenu script would be also very nice but so far I only needed XALL so just getting that bound would be fine.

Edit: Oh and having the submenu PREpend itself to the W menu is not the best thing : (
I'm used to W4 for removing doubles and this would've changed it to W5 so I needed to adjust the script to add itself to the bottom rather than the top. Glad that that was rather easy though.

**Comment by zeffii** [comment]
Hi, 

I tend to use the spacebar search menu instead of the W menu.  `space bar -> 'xa'` , and it will auto suggest XALL.

Regarding the 'Add Shortcut' not showing - that's interesting, I don't use that (Ever) but am surprised to see it doesn't show up. It might be an API thing where it only works for built in operators, i'll have a look around.

**Comment by BloodyRain2k** [comment]
Pushing the submenu to the bottom didn't change the xa search result so I'd say that's something that could be taken over without problems.
Regarding the adding, it might be a submenu issue, as the standalone version that added itself directly was bindable.
I'd also try other submenus for reference but I can't for the life of me remember where there's one...

**Comment by zeffii** [comment]
I mean I use the search menu triggered by the spacebar in 3dview. and then type in XA. Because the  XALL operator is usually the only operator registered that contains those two letters side by side it therefor auto-suggest XALL. Hitting enter then triggers the operator

![image](https://cloud.githubusercontent.com/assets/619340/14404111/3c7ebfe4-fe6f-11e5-8daf-dc4cd980c32c.png)

-------

I can't claim to understand why the option isn't available for this 'suite' .  Coming from autocad i like to use the `spacebar search` as a kind of console surrogate, where I can type the operator's shortname and execute it.

**Comment by zeffii** [comment]
as for Pie menus, that's a personal preference which I never really warmed to. I don't feel like dealing with the extra complexity for something I don't use..

But . the failure to show the `add shortcut`  option does bug me a little now :)

**Comment by BloodyRain2k** [comment]
Yeah I understood what you meant with the search menu, just noted that appending or prepending to the W menu does not affect that way of using it so I'd think appending by default would be the better option.

As for the pie menus, I like them for having more options on my mouse than I could ever fit normally onto it, but I can understand that it's overkill for this which isn't used that often.
I managed to get a menu assembled though but failed to make it auto load with blender, so I've just bound XAll to alt x by manually creating a keybind for 'tinycad.intersectall' :3

I hope you can figure something out for the add shortcut thing but for my end is everything fine again, and thanks for making this :D making intersection verts is a pain otherwise.

**Comment by zeffii** [comment]
the `append/prepend` menu positioning choice _could_ be a user setting. I just decided on prepending  while developing and didn't change it. I think this suits some people but not everyone. Again this is where I don't really have a firm desire to change it - I use the searchbar :). I've had a few requests to change the default to `append`, but not enough to move me.

**Comment by zeffii** [comment]
`Alt+X` is a nice combo.

**Comment by BloodyRain2k** [comment]
Want me to write you a pull request for that 3 letter change? :P
And yeah it is, was surprised it's even free, finding free keys in blender is like winning the lottery, just without cash xD

**Comment by zeffii** [comment]
lol! No. i won't accept that Pullrequest at this time.

and yes, free keys are like gold dust. : D

**Comment by zeffii** [comment]
apparently this 'Add Shortcut' is only added if the operator is registerd to a known `bpy.ops` namespace, like `bpy.ops.object` , i register tinycad operators to `bpy.ops.tinycad` . This is slightly arbitrary...in all perspectives.
Maybe there's a way to register tinycad to be picked up too..
